# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: "apkrash"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/apkrash/
    binary: apkrash

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: "kamushadenes"
    name: "apkrash"

  name_template: "{{.ProjectName}}-v{{.Version}}"
